# Generated by Django 5.2.6 on 2026-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ketahananpangan',
            name='jenis_usaha',
        ),
        migrations.AddField(
            model_name='ketahananpangan',
            name='usaha_lainnya',
            field=models.CharField(blank=True, help_text='Isi jika jenis usaha tidak tersedia', max_length=150),
        ),
        migrations.AddField(
            model_name='ketahananpangan',
            name='usaha_perdagangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ketahananpangan',
            name='usaha_perikanan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ketahananpangan',
            name='usaha_perladangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ketahananpangan',
            name='usaha_pertanian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ketahananpangan',
            name='usaha_peternakan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ketahananpangan',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/sk/'),
        ),
        migrations.AlterField(
            model_name='ketahananpangan',
            name='nomor_sk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='JenisUsaha',
        ),
    ]
