# Generated by Django 5.2.6 on 2026-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0002_remove_ketahananpangan_jenis_usaha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bltdd',
            name='jumlah_bulan',
            field=models.IntegerField(default=1),
        ),
    ]
