# Generated by Django 5.2.6 on 2026-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekbang', '0004_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
